spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS wallet_schema

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: wallet_schema

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: wallet_schema

logging:
  level:
    root: info

server:
  port: 8080

retryable:
  max-attempts: 5
  delay: 5000
